<a href="https://colab.research.google.com/github/ulrikSebastienR/Colab-python-diaries/blob/master/bb_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Blackboard Numpy
# python cheatsheet numpy
#      ndim: The number of axes or rank of the array
# shape: A tuple containing the length in each dimension
# size: The total number of elements
import numpy as np

In [2]:
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]
d = [10,11,12]
print(type(a))

<class 'list'>


In [3]:
a1 = np.array(a)
print(a1)
print(type(a1))
print(a1.shape)
print(a1.ndim)
print(a1.size)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
3


In [4]:
a2 = np.array([a,b]) #can't initiate numpy array without passing it as list of lists i.e. with a2 = np.array(a,b)
print(a2)
print(type(a2))
print(a2.shape)
print(a2.ndim)
print(a2.size)
print(a2.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2
6
int64


In [5]:
a3 = np.array([[a,b],[c,d]])
print(a3)
print(type(a3))
print(a3.ndim) #this is a 3-D array
print(a3.shape)
print(a3.size)
print(a3.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
(2, 2, 3)
12
int64
