<a href="https://colab.research.google.com/github/ulrikSebastienR/Colab-python-diaries/blob/master/Understanding_numpy_axes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

In [22]:
x = np.random.randint(1,1000,(5,4,3,2))
x

array([[[[981, 984],
         [ 54, 247],
         [708, 895]],

        [[666, 394],
         [ 53, 873],
         [893, 427]],

        [[696, 757],
         [394, 647],
         [ 24, 887]],

        [[276, 626],
         [304, 417],
         [299, 510]]],


       [[[571,  19],
         [464, 443],
         [102, 446]],

        [[581, 875],
         [886, 892],
         [330, 276]],

        [[705, 375],
         [737, 743],
         [808, 272]],

        [[890, 980],
         [442, 446],
         [316, 678]]],


       [[[739, 494],
         [218, 976],
         [141, 730]],

        [[463, 513],
         [476, 318],
         [357, 318]],

        [[504, 587],
         [379, 445],
         [550, 901]],

        [[905, 199],
         [596, 951],
         [144, 860]]],


       [[[121, 215],
         [402, 277],
         [648, 256]],

        [[261, 334],
         [169, 898],
         [921, 188]],

        [[280, 194],
         [695, 265],
         [ 56, 749]],

        [[129, 679]

In [23]:
x[0,:,:,:]


array([[[981, 984],
        [ 54, 247],
        [708, 895]],

       [[666, 394],
        [ 53, 873],
        [893, 427]],

       [[696, 757],
        [394, 647],
        [ 24, 887]],

       [[276, 626],
        [304, 417],
        [299, 510]]])

In [24]:
x[1,:,:,:]

array([[[571,  19],
        [464, 443],
        [102, 446]],

       [[581, 875],
        [886, 892],
        [330, 276]],

       [[705, 375],
        [737, 743],
        [808, 272]],

       [[890, 980],
        [442, 446],
        [316, 678]]])

In [25]:
x[:,0,:,:]


array([[[981, 984],
        [ 54, 247],
        [708, 895]],

       [[571,  19],
        [464, 443],
        [102, 446]],

       [[739, 494],
        [218, 976],
        [141, 730]],

       [[121, 215],
        [402, 277],
        [648, 256]],

       [[344, 276],
        [751, 969],
        [  1, 163]]])

In [26]:
x[:,1,:,:]

array([[[666, 394],
        [ 53, 873],
        [893, 427]],

       [[581, 875],
        [886, 892],
        [330, 276]],

       [[463, 513],
        [476, 318],
        [357, 318]],

       [[261, 334],
        [169, 898],
        [921, 188]],

       [[275,  29],
        [428, 359],
        [694, 636]]])

In [27]:
x[:,:,0,:]


array([[[981, 984],
        [666, 394],
        [696, 757],
        [276, 626]],

       [[571,  19],
        [581, 875],
        [705, 375],
        [890, 980]],

       [[739, 494],
        [463, 513],
        [504, 587],
        [905, 199]],

       [[121, 215],
        [261, 334],
        [280, 194],
        [129, 679]],

       [[344, 276],
        [275,  29],
        [ 61, 864],
        [880, 823]]])

In [28]:
x[:,:,1,:]

array([[[ 54, 247],
        [ 53, 873],
        [394, 647],
        [304, 417]],

       [[464, 443],
        [886, 892],
        [737, 743],
        [442, 446]],

       [[218, 976],
        [476, 318],
        [379, 445],
        [596, 951]],

       [[402, 277],
        [169, 898],
        [695, 265],
        [555, 706]],

       [[751, 969],
        [428, 359],
        [119, 104],
        [628, 209]]])

In [29]:
x[:,:,:,0]


array([[[981,  54, 708],
        [666,  53, 893],
        [696, 394,  24],
        [276, 304, 299]],

       [[571, 464, 102],
        [581, 886, 330],
        [705, 737, 808],
        [890, 442, 316]],

       [[739, 218, 141],
        [463, 476, 357],
        [504, 379, 550],
        [905, 596, 144]],

       [[121, 402, 648],
        [261, 169, 921],
        [280, 695,  56],
        [129, 555, 109]],

       [[344, 751,   1],
        [275, 428, 694],
        [ 61, 119, 568],
        [880, 628, 901]]])

In [30]:
x[:,:,:,1]

array([[[984, 247, 895],
        [394, 873, 427],
        [757, 647, 887],
        [626, 417, 510]],

       [[ 19, 443, 446],
        [875, 892, 276],
        [375, 743, 272],
        [980, 446, 678]],

       [[494, 976, 730],
        [513, 318, 318],
        [587, 445, 901],
        [199, 951, 860]],

       [[215, 277, 256],
        [334, 898, 188],
        [194, 265, 749],
        [679, 706, 810]],

       [[276, 969, 163],
        [ 29, 359, 636],
        [864, 104, 401],
        [823, 209, 513]]])

In [31]:
x=np.random.randint(1,100,(4,3,2))
x

array([[[39, 95],
        [94, 97],
        [94, 61]],

       [[ 3, 54],
        [ 9, 21],
        [61, 44]],

       [[24, 74],
        [48, 88],
        [86,  1]],

       [[ 1, 96],
        [94, 67],
        [87, 52]]])

In [32]:
x[0,:,:]


array([[39, 95],
       [94, 97],
       [94, 61]])

In [33]:
x[1,:,:]

array([[ 3, 54],
       [ 9, 21],
       [61, 44]])

In [34]:
x[:,0,:]


array([[39, 95],
       [ 3, 54],
       [24, 74],
       [ 1, 96]])

In [35]:
x[:,1,:]

array([[94, 97],
       [ 9, 21],
       [48, 88],
       [94, 67]])

In [36]:
x[:,:,0]


array([[39, 94, 94],
       [ 3,  9, 61],
       [24, 48, 86],
       [ 1, 94, 87]])

In [37]:
x[:,:,1]

array([[95, 97, 61],
       [54, 21, 44],
       [74, 88,  1],
       [96, 67, 52]])